<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    private $continentMap = [
        [6 => 'AF'],
        [1 => 'AL'],
        [3 => 'DZ'],
        [4 => 'AS'],
        [1 => 'AD'],
        [3 => 'AO'],
        [8 => 'AG'],
        [1 => 'AZ'],
        [6 => 'AZ'],
        [7 => 'AR'],
        [4 => 'AU'],
        [1 => 'AT'],
        [8 => 'BS'],
        [6 => 'BH'],
        [6 => 'BD'],
        [1 => 'AM'],
        [6 => 'AM'],
        [8 => 'BB'],
        [1 => 'BE'],
        [8 => 'BM'],
        [6 => 'BT'],
        [7 => 'BO'],
        [1 => 'BA'],
        [3 => 'BW'],
        [7 => 'BR'],
        [8 => 'BZ'],
        [6 => 'IO'],
        [4 => 'SB'],
        [8 => 'VG'],
        [6 => 'BN'],
        [1 => 'BG'],
        [6 => 'MM'],
        [3 => 'BI'],
        [1 => 'BY'],
        [6 => 'KH'],
        [3 => 'CM'],
        [5 => 'CA'],
        [3 => 'CV'],
        [8 => 'KY'],
        [3 => 'CF'],
        [6 => 'LK'],
        [3 => 'TD'],
        [7 => 'CL'],
        [6 => 'CN'],
        [6 => 'TW'],
        [6 => 'CX'],
        [6 => 'CC'],
        [7 => 'CO'],
        [3 => 'KM'],
        [3 => 'YT'],
        [3 => 'CG'],
        [3 => 'CD'],
        [4 => 'CK'],
        [8 => 'CR'],
        [1 => 'HR'],
        [8 => 'CU'],
        [1 => 'CY'],
        [6 => 'CY'],
        [1 => 'CZ'],
        [3 => 'BJ'],
        [1 => 'DK'],
        [8 => 'DM'],
        [8 => 'DO'],
        [7 => 'EC'],
        [8 => 'SV'],
        [3 => 'GQ'],
        [3 => 'ET'],
        [3 => 'ER'],
        [1 => 'EE'],
        [1 => 'FO'],
        [7 => 'FK'],
        [4 => 'FJ'],
        [1 => 'FI'],
        [1 => 'AX'],
        [1 => 'FR'],
        [7 => 'GF'],
        [4 => 'PF'],
        [3 => 'DJ'],
        [3 => 'GA'],
        [1 => 'GE'],
        [6 => 'GE'],
        [3 => 'GM'],
        [6 => 'PS'],
        [1 => 'DE'],
        [3 => 'GH'],
        [1 => 'GI'],
        [4 => 'KI'],
        [1 => 'GR'],
        [8 => 'GL'],
        [8 => 'GD'],
        [8 => 'GP'],
        [4 => 'GU'],
        [8 => 'GT'],
        [3 => 'GN'],
        [7 => 'GY'],
        [8 => 'HT'],
        [1 => 'VA'],
        [8 => 'HN'],
        [6 => 'HK'],
        [1 => 'HU'],
        [1 => 'IS'],
        [6 => 'IN'],
        [6 => 'ID'],
        [6 => 'IR'],
        [6 => 'IQ'],
        [1 => 'IE'],
        [6 => 'IL'],
        [1 => 'IT'],
        [3 => 'CI'],
        [8 => 'JM'],
        [6 => 'JP'],
        [1 => 'KZ'],
        [6 => 'KZ'],
        [6 => 'JO'],
        [3 => 'KE'],
        [6 => 'KP'],
        [6 => 'KR'],
        [6 => 'KW'],
        [6 => 'KG'],
        [6 => 'LA'],
        [6 => 'LB'],
        [3 => 'LS'],
        [1 => 'LV'],
        [3 => 'LR'],
        [3 => 'LY'],
        [1 => 'LI'],
        [1 => 'LT'],
        [1 => 'LU'],
        [6 => 'MO'],
        [3 => 'MG'],
        [3 => 'MW'],
        [6 => 'MY'],
        [6 => 'MV'],
        [3 => 'ML'],
        [1 => 'MT'],
        [8 => 'MQ'],
        [3 => 'MR'],
        [3 => 'MU'],
        [5 => 'MX'],
        [1 => 'MC'],
        [6 => 'MN'],
        [1 => 'MD'],
        [1 => 'ME'],
        [8 => 'MS'],
        [3 => 'MA'],
        [3 => 'MZ'],
        [6 => 'OM'],
        [3 => 'NA'],
        [4 => 'NR'],
        [6 => 'NP'],
        [1 => 'NL'],
        [8 => 'AN'],
        [8 => 'CW'],
        [8 => 'AW'],
        [8 => 'SX'],
        [8 => 'BQ'],
        [4 => 'NC'],
        [4 => 'VU'],
        [4 => 'NZ'],
        [8 => 'NI'],
        [3 => 'NE'],
        [3 => 'NG'],
        [4 => 'NU'],
        [4 => 'NF'],
        [1 => 'NO'],
        [4 => 'MP'],
        [4 => 'UM'],
        [8 => 'UM'],
        [4 => 'FM'],
        [4 => 'MH'],
        [4 => 'PW'],
        [6 => 'PK'],
        [8 => 'PA'],
        [4 => 'PG'],
        [7 => 'PY'],
        [7 => 'PE'],
        [6 => 'PH'],
        [4 => 'PN'],
        [1 => 'PL'],
        [1 => 'PT'],
        [3 => 'GW'],
        [6 => 'TL'],
        [8 => 'PR'],
        [6 => 'QA'],
        [3 => 'RE'],
        [1 => 'RO'],
        [1 => 'RU'],
        [6 => 'RU'],
        [3 => 'RW'],
        [8 => 'BL'],
        [3 => 'SH'],
        [8 => 'KN'],
        [8 => 'AI'],
        [8 => 'LC'],
        [8 => 'MF'],
        [8 => 'PM'],
        [8 => 'VC'],
        [1 => 'SM'],
        [3 => 'ST'],
        [6 => 'SA'],
        [3 => 'SN'],
        [1 => 'RS'],
        [3 => 'SC'],
        [3 => 'SL'],
        [6 => 'SG'],
        [1 => 'SK'],
        [6 => 'VN'],
        [1 => 'SI'],
        [3 => 'SO'],
        [3 => 'ZA'],
        [3 => 'ZW'],
        [1 => 'ES'],
        [3 => 'SS'],
        [3 => 'EH'],
        [3 => 'SD'],
        [7 => 'SR'],
        [1 => 'SJ'],
        [3 => 'SZ'],
        [1 => 'SE'],
        [1 => 'CH'],
        [6 => 'SY'],
        [6 => 'TJ'],
        [6 => 'TH'],
        [3 => 'TG'],
        [4 => 'TK'],
        [4 => 'TO'],
        [8 => 'TT'],
        [6 => 'AE'],
        [3 => 'TN'],
        [1 => 'TR'],
        [6 => 'TR'],
        [6 => 'TM'],
        [8 => 'TC'],
        [4 => 'TV'],
        [3 => 'UG'],
        [1 => 'UA'],
        [1 => 'MK'],
        [3 => 'EG'],
        [1 => 'GB'],
        [1 => 'GG'],
        [1 => 'JE'],
        [1 => 'IM'],
        [3 => 'TZ'],
        [5 => 'US'],
        [8 => 'VI'],
        [3 => 'BF'],
        [7 => 'UY'],
        [6 => 'UZ'],
        [7 => 'VE'],
        [4 => 'WF'],
        [4 => 'WS'],
        [6 => 'YE'],
        [3 => 'ZM'],
        [4 => 'XX'],
        [6 => 'XE'],
        [6 => 'XD'],
        [6 => 'XS'],
    ];

    private $data = [
        ['id' => 1, 'alpha-2_code' => 'AF', 'name' => 'Afghanistan'],
        ['id' => 2, 'alpha-2_code' => 'AX', 'name' => 'Åland Islands'],
        ['id' => 3, 'alpha-2_code' => 'AL', 'name' => 'Albania'],
        ['id' => 4, 'alpha-2_code' => 'DZ', 'name' => 'Algeria'],
        ['id' => 5, 'alpha-2_code' => 'AS', 'name' => 'American Samoa'],
        ['id' => 6, 'alpha-2_code' => 'AD', 'name' => 'Andorra'],
        ['id' => 7, 'alpha-2_code' => 'AO', 'name' => 'Angola'],
        ['id' => 8, 'alpha-2_code' => 'AI', 'name' => 'Anguilla'],
        ['id' => 9, 'alpha-2_code' => 'AQ', 'name' => 'Antarctica'],
        ['id' => 10, 'alpha-2_code' => 'AG', 'name' => 'Antigua & Barbuda'],
        ['id' => 11, 'alpha-2_code' => 'AR', 'name' => 'Argentina'],
        ['id' => 12, 'alpha-2_code' => 'AM', 'name' => 'Armenia'],
        ['id' => 13, 'alpha-2_code' => 'AW', 'name' => 'Aruba'],
        ['id' => 14, 'alpha-2_code' => 'AC', 'name' => 'Ascension Island'],
        ['id' => 15, 'alpha-2_code' => 'AU', 'name' => 'Australia'],
        ['id' => 16, 'alpha-2_code' => 'AT', 'name' => 'Austria'],
        ['id' => 17, 'alpha-2_code' => 'AZ', 'name' => 'Azerbaijan'],
        ['id' => 18, 'alpha-2_code' => 'BS', 'name' => 'Bahamas'],
        ['id' => 19, 'alpha-2_code' => 'BH', 'name' => 'Bahrain'],
        ['id' => 20, 'alpha-2_code' => 'BD', 'name' => 'Bangladesh'],
        ['id' => 21, 'alpha-2_code' => 'BB', 'name' => 'Barbados'],
        ['id' => 22, 'alpha-2_code' => 'BY', 'name' => 'Belarus'],
        ['id' => 23, 'alpha-2_code' => 'BE', 'name' => 'Belgium'],
        ['id' => 24, 'alpha-2_code' => 'BZ', 'name' => 'Belize'],
        ['id' => 25, 'alpha-2_code' => 'BJ', 'name' => 'Benin'],
        ['id' => 26, 'alpha-2_code' => 'BM', 'name' => 'Bermuda'],
        ['id' => 27, 'alpha-2_code' => 'BT', 'name' => 'Bhutan'],
        ['id' => 28, 'alpha-2_code' => 'BO', 'name' => 'Bolivia'],
        ['id' => 29, 'alpha-2_code' => 'BA', 'name' => 'Bosnia & Herzegovina'],
        ['id' => 30, 'alpha-2_code' => 'BW', 'name' => 'Botswana'],
        ['id' => 31, 'alpha-2_code' => 'BR', 'name' => 'Brazil'],
        ['id' => 32, 'alpha-2_code' => 'IO', 'name' => 'British Indian Ocean Territory'],
        ['id' => 33, 'alpha-2_code' => 'VG', 'name' => 'British Virgin Islands'],
        ['id' => 34, 'alpha-2_code' => 'BN', 'name' => 'Brunei'],
        ['id' => 35, 'alpha-2_code' => 'BG', 'name' => 'Bulgaria'],
        ['id' => 36, 'alpha-2_code' => 'BF', 'name' => 'Burkina Faso'],
        ['id' => 37, 'alpha-2_code' => 'BI', 'name' => 'Burundi'],
        ['id' => 38, 'alpha-2_code' => 'KH', 'name' => 'Cambodia'],
        ['id' => 39, 'alpha-2_code' => 'CM', 'name' => 'Cameroon'],
        ['id' => 40, 'alpha-2_code' => 'CA', 'name' => 'Canada'],
        ['id' => 41, 'alpha-2_code' => 'IC', 'name' => 'Canary Islands'],
        ['id' => 42, 'alpha-2_code' => 'CV', 'name' => 'Cape Verde'],
        ['id' => 43, 'alpha-2_code' => 'BQ', 'name' => 'Caribbean Netherlands'],
        ['id' => 44, 'alpha-2_code' => 'KY', 'name' => 'Cayman Islands'],
        ['id' => 45, 'alpha-2_code' => 'CF', 'name' => 'Central African Republic'],
        ['id' => 46, 'alpha-2_code' => 'EA', 'name' => 'Ceuta & Melilla'],
        ['id' => 47, 'alpha-2_code' => 'TD', 'name' => 'Chad'],
        ['id' => 48, 'alpha-2_code' => 'CL', 'name' => 'Chile'],
        ['id' => 49, 'alpha-2_code' => 'CN', 'name' => 'China'],
        ['id' => 50, 'alpha-2_code' => 'CX', 'name' => 'Christmas Island'],
        ['id' => 51, 'alpha-2_code' => 'CC', 'name' => 'Cocos (Keeling) Islands'],
        ['id' => 52, 'alpha-2_code' => 'CO', 'name' => 'Colombia'],
        ['id' => 53, 'alpha-2_code' => 'KM', 'name' => 'Comoros'],
        ['id' => 54, 'alpha-2_code' => 'CG', 'name' => 'Congo - Brazzaville'],
        ['id' => 55, 'alpha-2_code' => 'CD', 'name' => 'Congo - Kinshasa'],
        ['id' => 56, 'alpha-2_code' => 'CK', 'name' => 'Cook Islands'],
        ['id' => 57, 'alpha-2_code' => 'CR', 'name' => 'Costa Rica'],
        ['id' => 58, 'alpha-2_code' => 'CI', 'name' => 'Côte d’Ivoire'],
        ['id' => 59, 'alpha-2_code' => 'HR', 'name' => 'Croatia'],
        ['id' => 60, 'alpha-2_code' => 'CU', 'name' => 'Cuba'],
        ['id' => 61, 'alpha-2_code' => 'CW', 'name' => 'Curaçao'],
        ['id' => 62, 'alpha-2_code' => 'CY', 'name' => 'Cyprus'],
        ['id' => 63, 'alpha-2_code' => 'CZ', 'name' => 'Czechia'],
        ['id' => 64, 'alpha-2_code' => 'DK', 'name' => 'Denmark'],
        ['id' => 65, 'alpha-2_code' => 'DG', 'name' => 'Diego Garcia'],
        ['id' => 66, 'alpha-2_code' => 'DJ', 'name' => 'Djibouti'],
        ['id' => 67, 'alpha-2_code' => 'DM', 'name' => 'Dominica'],
        ['id' => 68, 'alpha-2_code' => 'DO', 'name' => 'Dominican Republic'],
        ['id' => 69, 'alpha-2_code' => 'EC', 'name' => 'Ecuador'],
        ['id' => 70, 'alpha-2_code' => 'EG', 'name' => 'Egypt'],
        ['id' => 71, 'alpha-2_code' => 'SV', 'name' => 'El Salvador'],
        ['id' => 72, 'alpha-2_code' => 'GQ', 'name' => 'Equatorial Guinea'],
        ['id' => 73, 'alpha-2_code' => 'ER', 'name' => 'Eritrea'],
        ['id' => 74, 'alpha-2_code' => 'EE', 'name' => 'Estonia'],
        ['id' => 75, 'alpha-2_code' => 'SZ', 'name' => 'Eswatini'],
        ['id' => 76, 'alpha-2_code' => 'ET', 'name' => 'Ethiopia'],
        ['id' => 77, 'alpha-2_code' => 'FK', 'name' => 'Falkland Islands'],
        ['id' => 78, 'alpha-2_code' => 'FO', 'name' => 'Faroe Islands'],
        ['id' => 79, 'alpha-2_code' => 'FJ', 'name' => 'Fiji'],
        ['id' => 80, 'alpha-2_code' => 'FI', 'name' => 'Finland'],
        ['id' => 81, 'alpha-2_code' => 'FR', 'name' => 'France'],
        ['id' => 82, 'alpha-2_code' => 'GF', 'name' => 'French Guiana'],
        ['id' => 83, 'alpha-2_code' => 'PF', 'name' => 'French Polynesia'],
        ['id' => 84, 'alpha-2_code' => 'TF', 'name' => 'French Southern Territories'],
        ['id' => 85, 'alpha-2_code' => 'GA', 'name' => 'Gabon'],
        ['id' => 86, 'alpha-2_code' => 'GM', 'name' => 'Gambia'],
        ['id' => 87, 'alpha-2_code' => 'GE', 'name' => 'Georgia'],
        ['id' => 88, 'alpha-2_code' => 'DE', 'name' => 'Germany'],
        ['id' => 89, 'alpha-2_code' => 'GH', 'name' => 'Ghana'],
        ['id' => 90, 'alpha-2_code' => 'GI', 'name' => 'Gibraltar'],
        ['id' => 91, 'alpha-2_code' => 'GR', 'name' => 'Greece'],
        ['id' => 92, 'alpha-2_code' => 'GL', 'name' => 'Greenland'],
        ['id' => 93, 'alpha-2_code' => 'GD', 'name' => 'Grenada'],
        ['id' => 94, 'alpha-2_code' => 'GP', 'name' => 'Guadeloupe'],
        ['id' => 95, 'alpha-2_code' => 'GU', 'name' => 'Guam'],
        ['id' => 96, 'alpha-2_code' => 'GT', 'name' => 'Guatemala'],
        ['id' => 97, 'alpha-2_code' => 'GG', 'name' => 'Guernsey'],
        ['id' => 98, 'alpha-2_code' => 'GN', 'name' => 'Guinea'],
        ['id' => 99, 'alpha-2_code' => 'GW', 'name' => 'Guinea-Bissau'],
        ['id' => 100, 'alpha-2_code' => 'GY', 'name' => 'Guyana'],
        ['id' => 101, 'alpha-2_code' => 'HT', 'name' => 'Haiti'],
        ['id' => 102, 'alpha-2_code' => 'HN', 'name' => 'Honduras'],
        ['id' => 103, 'alpha-2_code' => 'HK', 'name' => 'Hong Kong SAR China'],
        ['id' => 104, 'alpha-2_code' => 'HU', 'name' => 'Hungary'],
        ['id' => 105, 'alpha-2_code' => 'IS', 'name' => 'Iceland'],
        ['id' => 106, 'alpha-2_code' => 'IN', 'name' => 'India'],
        ['id' => 107, 'alpha-2_code' => 'ID', 'name' => 'Indonesia'],
        ['id' => 108, 'alpha-2_code' => 'IR', 'name' => 'Iran'],
        ['id' => 109, 'alpha-2_code' => 'IQ', 'name' => 'Iraq'],
        ['id' => 110, 'alpha-2_code' => 'IE', 'name' => 'Ireland'],
        ['id' => 111, 'alpha-2_code' => 'IM', 'name' => 'Isle of Man'],
        ['id' => 112, 'alpha-2_code' => 'IL', 'name' => 'Israel'],
        ['id' => 113, 'alpha-2_code' => 'IT', 'name' => 'Italy'],
        ['id' => 114, 'alpha-2_code' => 'JM', 'name' => 'Jamaica'],
        ['id' => 115, 'alpha-2_code' => 'JP', 'name' => 'Japan'],
        ['id' => 116, 'alpha-2_code' => 'JE', 'name' => 'Jersey'],
        ['id' => 117, 'alpha-2_code' => 'JO', 'name' => 'Jordan'],
        ['id' => 118, 'alpha-2_code' => 'KZ', 'name' => 'Kazakhstan'],
        ['id' => 119, 'alpha-2_code' => 'KE', 'name' => 'Kenya'],
        ['id' => 120, 'alpha-2_code' => 'KI', 'name' => 'Kiribati'],
        ['id' => 121, 'alpha-2_code' => 'XK', 'name' => 'Kosovo'],
        ['id' => 122, 'alpha-2_code' => 'KW', 'name' => 'Kuwait'],
        ['id' => 123, 'alpha-2_code' => 'KG', 'name' => 'Kyrgyzstan'],
        ['id' => 124, 'alpha-2_code' => 'LA', 'name' => 'Laos'],
        ['id' => 125, 'alpha-2_code' => 'LV', 'name' => 'Latvia'],
        ['id' => 126, 'alpha-2_code' => 'LB', 'name' => 'Lebanon'],
        ['id' => 127, 'alpha-2_code' => 'LS', 'name' => 'Lesotho'],
        ['id' => 128, 'alpha-2_code' => 'LR', 'name' => 'Liberia'],
        ['id' => 129, 'alpha-2_code' => 'LY', 'name' => 'Libya'],
        ['id' => 130, 'alpha-2_code' => 'LI', 'name' => 'Liechtenstein'],
        ['id' => 131, 'alpha-2_code' => 'LT', 'name' => 'Lithuania'],
        ['id' => 132, 'alpha-2_code' => 'LU', 'name' => 'Luxembourg'],
        ['id' => 133, 'alpha-2_code' => 'MO', 'name' => 'Macao SAR China'],
        ['id' => 134, 'alpha-2_code' => 'MG', 'name' => 'Madagascar'],
        ['id' => 135, 'alpha-2_code' => 'MW', 'name' => 'Malawi'],
        ['id' => 136, 'alpha-2_code' => 'MY', 'name' => 'Malaysia'],
        ['id' => 137, 'alpha-2_code' => 'MV', 'name' => 'Maldives'],
        ['id' => 138, 'alpha-2_code' => 'ML', 'name' => 'Mali'],
        ['id' => 139, 'alpha-2_code' => 'MT', 'name' => 'Malta'],
        ['id' => 140, 'alpha-2_code' => 'MH', 'name' => 'Marshall Islands'],
        ['id' => 141, 'alpha-2_code' => 'MQ', 'name' => 'Martinique'],
        ['id' => 142, 'alpha-2_code' => 'MR', 'name' => 'Mauritania'],
        ['id' => 143, 'alpha-2_code' => 'MU', 'name' => 'Mauritius'],
        ['id' => 144, 'alpha-2_code' => 'YT', 'name' => 'Mayotte'],
        ['id' => 145, 'alpha-2_code' => 'MX', 'name' => 'Mexico'],
        ['id' => 146, 'alpha-2_code' => 'FM', 'name' => 'Micronesia'],
        ['id' => 147, 'alpha-2_code' => 'MD', 'name' => 'Moldova'],
        ['id' => 148, 'alpha-2_code' => 'MC', 'name' => 'Monaco'],
        ['id' => 149, 'alpha-2_code' => 'MN', 'name' => 'Mongolia'],
        ['id' => 150, 'alpha-2_code' => 'ME', 'name' => 'Montenegro'],
        ['id' => 151, 'alpha-2_code' => 'MS', 'name' => 'Montserrat'],
        ['id' => 152, 'alpha-2_code' => 'MA', 'name' => 'Morocco'],
        ['id' => 153, 'alpha-2_code' => 'MZ', 'name' => 'Mozambique'],
        ['id' => 154, 'alpha-2_code' => 'MM', 'name' => 'Myanmar (Burma)'],
        ['id' => 155, 'alpha-2_code' => 'NA', 'name' => 'Namibia'],
        ['id' => 156, 'alpha-2_code' => 'NR', 'name' => 'Nauru'],
        ['id' => 157, 'alpha-2_code' => 'NP', 'name' => 'Nepal'],
        ['id' => 158, 'alpha-2_code' => 'NL', 'name' => 'Netherlands'],
        ['id' => 159, 'alpha-2_code' => 'NC', 'name' => 'New Caledonia'],
        ['id' => 160, 'alpha-2_code' => 'NZ', 'name' => 'New Zealand'],
        ['id' => 161, 'alpha-2_code' => 'NI', 'name' => 'Nicaragua'],
        ['id' => 162, 'alpha-2_code' => 'NE', 'name' => 'Niger'],
        ['id' => 163, 'alpha-2_code' => 'NG', 'name' => 'Nigeria'],
        ['id' => 164, 'alpha-2_code' => 'NU', 'name' => 'Niue'],
        ['id' => 165, 'alpha-2_code' => 'NF', 'name' => 'Norfolk Island'],
        ['id' => 166, 'alpha-2_code' => 'KP', 'name' => 'North Korea'],
        ['id' => 167, 'alpha-2_code' => 'MK', 'name' => 'North Macedonia'],
        ['id' => 168, 'alpha-2_code' => 'MP', 'name' => 'Northern Mariana Islands'],
        ['id' => 169, 'alpha-2_code' => 'NO', 'name' => 'Norway'],
        ['id' => 170, 'alpha-2_code' => 'OM', 'name' => 'Oman'],
        ['id' => 171, 'alpha-2_code' => 'PK', 'name' => 'Pakistan'],
        ['id' => 172, 'alpha-2_code' => 'PW', 'name' => 'Palau'],
        ['id' => 173, 'alpha-2_code' => 'PS', 'name' => 'Palestinian Territories'],
        ['id' => 174, 'alpha-2_code' => 'PA', 'name' => 'Panama'],
        ['id' => 175, 'alpha-2_code' => 'PG', 'name' => 'Papua New Guinea'],
        ['id' => 176, 'alpha-2_code' => 'PY', 'name' => 'Paraguay'],
        ['id' => 177, 'alpha-2_code' => 'PE', 'name' => 'Peru'],
        ['id' => 178, 'alpha-2_code' => 'PH', 'name' => 'Philippines'],
        ['id' => 179, 'alpha-2_code' => 'PN', 'name' => 'Pitcairn Islands'],
        ['id' => 180, 'alpha-2_code' => 'PL', 'name' => 'Poland'],
        ['id' => 181, 'alpha-2_code' => 'PT', 'name' => 'Portugal'],
        ['id' => 182, 'alpha-2_code' => 'XA', 'name' => 'Pseudo-Accents'],
        ['id' => 183, 'alpha-2_code' => 'XB', 'name' => 'Pseudo-Bidi'],
        ['id' => 184, 'alpha-2_code' => 'PR', 'name' => 'Puerto Rico'],
        ['id' => 185, 'alpha-2_code' => 'QA', 'name' => 'Qatar'],
        ['id' => 186, 'alpha-2_code' => 'RE', 'name' => 'Réunion'],
        ['id' => 187, 'alpha-2_code' => 'RO', 'name' => 'Romania'],
        ['id' => 188, 'alpha-2_code' => 'RU', 'name' => 'Russia'],
        ['id' => 189, 'alpha-2_code' => 'RW', 'name' => 'Rwanda'],
        ['id' => 190, 'alpha-2_code' => 'WS', 'name' => 'Samoa'],
        ['id' => 191, 'alpha-2_code' => 'SM', 'name' => 'San Marino'],
        ['id' => 192, 'alpha-2_code' => 'ST', 'name' => 'São Tomé & Príncipe'],
        ['id' => 193, 'alpha-2_code' => 'SA', 'name' => 'Saudi Arabia'],
        ['id' => 194, 'alpha-2_code' => 'SN', 'name' => 'Senegal'],
        ['id' => 195, 'alpha-2_code' => 'RS', 'name' => 'Serbia'],
        ['id' => 196, 'alpha-2_code' => 'SC', 'name' => 'Seychelles'],
        ['id' => 197, 'alpha-2_code' => 'SL', 'name' => 'Sierra Leone'],
        ['id' => 198, 'alpha-2_code' => 'SG', 'name' => 'Singapore'],
        ['id' => 199, 'alpha-2_code' => 'SX', 'name' => 'Sint Maarten'],
        ['id' => 200, 'alpha-2_code' => 'SK', 'name' => 'Slovakia'],
        ['id' => 201, 'alpha-2_code' => 'SI', 'name' => 'Slovenia'],
        ['id' => 202, 'alpha-2_code' => 'SB', 'name' => 'Solomon Islands'],
        ['id' => 203, 'alpha-2_code' => 'SO', 'name' => 'Somalia'],
        ['id' => 204, 'alpha-2_code' => 'ZA', 'name' => 'South Africa'],
        ['id' => 205, 'alpha-2_code' => 'GS', 'name' => 'South Georgia & South Sandwich Islands'],
        ['id' => 206, 'alpha-2_code' => 'KR', 'name' => 'South Korea'],
        ['id' => 207, 'alpha-2_code' => 'SS', 'name' => 'South Sudan'],
        ['id' => 208, 'alpha-2_code' => 'ES', 'name' => 'Spain'],
        ['id' => 209, 'alpha-2_code' => 'LK', 'name' => 'Sri Lanka'],
        ['id' => 210, 'alpha-2_code' => 'BL', 'name' => 'St. Barthélemy'],
        ['id' => 211, 'alpha-2_code' => 'SH', 'name' => 'St. Helena'],
        ['id' => 212, 'alpha-2_code' => 'KN', 'name' => 'St. Kitts & Nevis'],
        ['id' => 213, 'alpha-2_code' => 'LC', 'name' => 'St. Lucia'],
        ['id' => 214, 'alpha-2_code' => 'MF', 'name' => 'St. Martin'],
        ['id' => 215, 'alpha-2_code' => 'PM', 'name' => 'St. Pierre & Miquelon'],
        ['id' => 216, 'alpha-2_code' => 'VC', 'name' => 'St. Vincent & Grenadines'],
        ['id' => 217, 'alpha-2_code' => 'SD', 'name' => 'Sudan'],
        ['id' => 218, 'alpha-2_code' => 'SR', 'name' => 'Suriname'],
        ['id' => 219, 'alpha-2_code' => 'SJ', 'name' => 'Svalbard & Jan Mayen'],
        ['id' => 220, 'alpha-2_code' => 'SE', 'name' => 'Sweden'],
        ['id' => 221, 'alpha-2_code' => 'CH', 'name' => 'Switzerland'],
        ['id' => 222, 'alpha-2_code' => 'SY', 'name' => 'Syria'],
        ['id' => 223, 'alpha-2_code' => 'TW', 'name' => 'Taiwan'],
        ['id' => 224, 'alpha-2_code' => 'TJ', 'name' => 'Tajikistan'],
        ['id' => 225, 'alpha-2_code' => 'TZ', 'name' => 'Tanzania'],
        ['id' => 226, 'alpha-2_code' => 'TH', 'name' => 'Thailand'],
        ['id' => 227, 'alpha-2_code' => 'TL', 'name' => 'Timor-Leste'],
        ['id' => 228, 'alpha-2_code' => 'TG', 'name' => 'Togo'],
        ['id' => 229, 'alpha-2_code' => 'TK', 'name' => 'Tokelau'],
        ['id' => 230, 'alpha-2_code' => 'TO', 'name' => 'Tonga'],
        ['id' => 231, 'alpha-2_code' => 'TT', 'name' => 'Trinidad & Tobago'],
        ['id' => 232, 'alpha-2_code' => 'TA', 'name' => 'Tristan da Cunha'],
        ['id' => 233, 'alpha-2_code' => 'TN', 'name' => 'Tunisia'],
        ['id' => 234, 'alpha-2_code' => 'TR', 'name' => 'Turkey'],
        ['id' => 235, 'alpha-2_code' => 'TM', 'name' => 'Turkmenistan'],
        ['id' => 236, 'alpha-2_code' => 'TC', 'name' => 'Turks & Caicos Islands'],
        ['id' => 237, 'alpha-2_code' => 'TV', 'name' => 'Tuvalu'],
        ['id' => 238, 'alpha-2_code' => 'UM', 'name' => 'U.S. Outlying Islands'],
        ['id' => 239, 'alpha-2_code' => 'VI', 'name' => 'U.S. Virgin Islands'],
        ['id' => 240, 'alpha-2_code' => 'UG', 'name' => 'Uganda'],
        ['id' => 241, 'alpha-2_code' => 'UA', 'name' => 'Ukraine'],
        ['id' => 242, 'alpha-2_code' => 'AE', 'name' => 'United Arab Emirates'],
        ['id' => 243, 'alpha-2_code' => 'GB', 'name' => 'United Kingdom'],
        ['id' => 244, 'alpha-2_code' => 'US', 'name' => 'United States'],
        ['id' => 245, 'alpha-2_code' => 'UY', 'name' => 'Uruguay'],
        ['id' => 246, 'alpha-2_code' => 'UZ', 'name' => 'Uzbekistan'],
        ['id' => 247, 'alpha-2_code' => 'VU', 'name' => 'Vanuatu'],
        ['id' => 248, 'alpha-2_code' => 'VA', 'name' => 'Vatican City'],
        ['id' => 249, 'alpha-2_code' => 'VE', 'name' => 'Venezuela'],
        ['id' => 250, 'alpha-2_code' => 'VN', 'name' => 'Vietnam'],
        ['id' => 251, 'alpha-2_code' => 'WF', 'name' => 'Wallis & Futuna'],
        ['id' => 252, 'alpha-2_code' => 'EH', 'name' => 'Western Sahara'],
        ['id' => 253, 'alpha-2_code' => 'YE', 'name' => 'Yemen'],
        ['id' => 254, 'alpha-2_code' => 'ZM', 'name' => 'Zambia'],
        ['id' => 255, 'alpha-2_code' => 'ZW', 'name' => 'Zimbabwe'],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->data as $entry) {
            $data = array();

            foreach ($entry as $key => $value) {
                if ($key === 'id') {
                    continue;
                }

                $data[$key] = $value;
            }

            DB::table('countries')->updateOrInsert(['id' => $entry['id']], $data);
        }

        foreach ($this->continentMap as $stuff) {
            foreach ($stuff as $key => $value) {
                $country = Country::where('alpha-2_code', $value)->first();

                if (!$country) {
                    continue;
                }

                $country->continent_id = $key;
                $country->save();
            }
        }
    }
}
