php:
  preset: laravel
  version: 8
  disabled:
    - no_unused_imports
    - binary_operator_spaces
    - not_operator_with_successor_space
  finder:
    not-name:
      - index.php
      - server.php
      - _ide_helper.php
      - _ide_helper_models.php
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
